# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bmse <- function(vals) {
    .Call('ngspatial_bmse', PACKAGE = 'ngspatial', vals)
}

rautologistic_ <- function(X, A, theta) {
    .Call('ngspatial_rautologistic_', PACKAGE = 'ngspatial', X, A, theta)
}

randWalk <- function(X, A, Z, theta, tol, minit, maxit, sigma, etaRange, V, verbose) {
    .Call('ngspatial_randWalk', PACKAGE = 'ngspatial', X, A, Z, theta, tol, minit, maxit, sigma, etaRange, V, verbose)
}

randWalkTrain <- function(X, A, Z, theta, trainit, sigma, etaRange, V, verbose) {
    .Call('ngspatial_randWalkTrain', PACKAGE = 'ngspatial', X, A, Z, theta, trainit, sigma, etaRange, V, verbose)
}

